import type { Metadata } from "next";

import "./globals.css";
import { Providers } from "./providers";


export const metadata: Metadata = {
  title: "Arcus",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">

      <body
        className={`antialiased`}
      >
        <Providers>

          {children}
        </Providers>
      </body>
    </html>
  );
}
