import type { Metadata } from 'next'

import { NextIntlClientProvider } from 'next-intl'
import { getMessages, unstable_setRequestLocale } from 'next-intl/server'
import { routing } from '@/i18n/routing'
import { Providers } from '../providers'
import './globals.css'

export const metadata: Metadata = {
  title: 'Arcus',
  description: 'Generated by create next app',
}

// Pre-render one page per supported locale at build time (required for `output: 'export'`).
export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }))
}

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode
  params: { locale: string }
}>) {
  // Enable static rendering: makes the request locale available without middleware.
  unstable_setRequestLocale(locale)

  const messages = await getMessages()

  return (
    <html lang={locale}>
      <body className={`antialiased`}>
        <NextIntlClientProvider messages={messages}>
          <Providers>{children}</Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
